### ISSUE TITLE
Rename "Show All" checkbox

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#100]
Tab Assessment/Endpoint data used/Selection of endpoints

* Change the checkbox title to “Show all endpoints” 
* Change the link to point to selected substances only (depending on the checkbox state)

**Comment by gonzomir** [comment]
I renamed the checkbox, but what link we are talking about? The tabs "Search substance(s)" / "Selection of endpoints" work independent from the state of the checkbox, and so do the main tabs at the top.

**Comment by vedina** [comment]
Tab [Endpoint data used] , subtab [Selection of endpoints]. The endpoint list (and the numbers shown) are retrieved by different queries, dependent on the checkbox.

**Comment by gonzomir** [comment]
But the URL of the query is changed by the checkbox. When the tab is selected, it inspects the state of the checkbox. No need for additional work here.

**Comment by vedina** [comment]
Then fine !
