### ISSUE TITLE
Change the endpoint columns ordering

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#102]
In *Assessment/Assessment details/ matrix*

Please change the sequence of endpoint data according to the chapter number: e.g. 4.3 , 5.2.1 , 6.1.1 

![image](https://cloud.githubusercontent.com/assets/211190/6614672/432840be-c8a5-11e4-9095-3304e20cd9c3.png)

The JSON contains a numeric value for each endpoint category, which is used for ordering in the [study display](https://apps.ideaconsult.net/opentox/substance/IUC4-28046eb0-0a7f-3778-bb82-6b1f216dd381/study) and could be reused here.

**Comment by gonzomir** [comment]
The columns are ordered by the column title. Since it starts with the numeric value, the sorting is actually done by that value.

**Comment by gonzomir** [comment]
The groups that hold the column identifiers need sorting too, because the table is rendered first by group and then by columns in the group. The sorting of the groups kind of hacky - we try to put the properties of an object in a particular order, which is not guaranteed to always work.

**Comment by vedina** [comment]
Isn't the group exactly the same as the column (the column itself can contain multiple properties, but they are all of the same endpoint category, which is how the group is formed).

Otherwise works as expected.
