### ISSUE TITLE
Assessment details / Matrix results representation

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#104]
To be presented in more details (top - current, bottom - requested)

![image](https://cloud.githubusercontent.com/assets/211190/6615075/5b42003c-c8a9-11e4-80ec-12f91809fe8f.png)

All the information is available in the dataset/ study JSON, find out how to generalize the presentation.

**Comment by gonzomir** [comment]
I hope I got it right, added the feature.creator field in front of the value. Changes are in matrix_rearrangements branch.

**Comment by vedina** [comment]
This is more complicated, the creator might be added only for some endpoint, not for all, also  conditions could be displayed.

**Comment by vedina** [comment]
Use the configuration from [/scripts/config-study.js](https://apps.ideaconsult.net/data/scripts/config-study.js)  (the same config used in jToxStudy )

Display only fields assigned  "isInMatrix:true". 

Given the study JSON  the rule looks like (some items may be empty)
* Endpoint = value units (parameters, conditions, guideline)
or
* Interpretation of results (parameters, conditions, guideline)

Given the dataset / feature representation

````
feature.title = value feature.units ( all instances of feature.annotation.o , feature.creator (can be shortened) )
````

The dataset/features JSON is generated from study JSON roughly as follows
   * feature.title- effect.endpoints
   * feature.annotation.o of type conditions : conditions
   * feature.annotation.o of type parameters: parameters
   * feature.creator

Not all conditions should be visible - check the inMatrix field to decide if a field is visible.

Example

* display in matrix
````
LD50 > 5000 mg/kg bw (rat)
````

* config
````json
"TO_ACUTE_ORAL_SECTION": {
            "parameters": {
                "species": {
                    "iOrder": -7,
                    "inMatrix" : true
                }
            },
            "conditions": {
                "sex": {
                    "iOrder": -4
                }
            },
            "effects": {
                "endpoint": {
                    "iOrder": -6,
                    "inMatrix" : true
                },
                "result": {
                    "sTitle": "Value",
                    "iOrder": -5,
                    "inMatrix" : true
                }
            },
            "protocol": {
                "guideline": {
                    "iOrder": -1
                },
                "citation": {
                    "bVisible": true
                }                
            },
            "interpretation": {
                "result": {
                    "iOrder": -3,
                    "sTitle": "Interpretation of the results"
                },
                "criteria": {
                    "iOrder": -2
                }
            }
        },
````

The

**Comment by vedina** [comment]
works nice

Could you use the `sTitle` field to show condition names instead the field name?

````
            "conditions": {
                "atm. pressure": {
                    "sTitle": "Pressure",
                    "inMatrix": true
                }
````
