### ISSUE TITLE
bundle JSON new fields

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#106]
The bundle JSON is updated with the following new fields 

* _number_  - identifier of the bundle and all of it versions ( the existing field _id_ is unique for each version)
* _version_ - The version
* _updated_ - Timestamp of the last update
* _status_ - One of published,draft,archived
* _bundleversions_ - URI listing all versions of the bundle

Example:
```json
{"dataset": [
{
	"URI":"https://host/ambit/bundle/2",
	"type":"Bundle",
	"title":"Test assessment",
	"stars":5,
	"source":"Default",
	"rightsHolder":"Example",
	"maintainer":"Example",
	"seeAlso":"http://ambit.sourceforge.net",
	"rights":{
		"URI":"http://ambit.sf.net/resolver/rights/",
		"type":"rights"
	},
	"id":2,
	"number":"00000000-0000-0000-0000-000000000002",
	"version":1,
	"owner":"guest",
	"description":"The description",
	"created":1420627073000,
	"updated":1420627073000,
	"status":"draft",
	"summary":"https://host/ambit2/bundle/2/summary",
	"compound":"https://host/ambit2/bundle/2/compound",
	"substance":"https://host/ambit2/bundle/2/substance",
	"property":"https://host/ambit2/bundle/2/property",
	"dataset":"https://host/ambit2/bundle/2/dataset",
	"matrix":"https://host/ambit2/bundle/2/matrix",
	"bundleversions":"https://host/ambit2/bundle/2/version"
},
````

Please update as follows:
* The Assessment Identifier tab to show the _number_ as the assessment id ; 
* Change the finalized field to show the last updated time stamp; 
* Replace the "Date finalized" caption with  "Version last modified on"
* Change the _Published_ field to be displayed as a drop down box with list values: _yes_, _no_ .  
     * Display _yes_ when status='published' ;  
     * otherwise display _no_ . 
* Replace the "Date started" caption with  "Version start date"
* Remove "Use allowed" 
* Remove "Flags"
* Order the fields 
  1. Name
  2. Owner
  3. Purpose
  4. Version
  5. Status
  6. Version start date (former *Date started*)
  7. Version last modified on (former *Date finished*)
  8. Published
  9.  License of Waiver
  10.	 Rights holder
  11.	 Source
  12.	 Source URL
  13.	 Assessment ID (former *Assessment*, not bold )

![image](https://cloud.githubusercontent.com/assets/211190/6615394/4d07819c-c8ac-11e4-9469-bf99218f226f.png)

**Comment by gonzomir** [comment]
The Assessment Identifier tab is update with new data. It looks thou that the `updated` field does not update when something in the bundle changes.

**Comment by vedina** [comment]
The [PUT /bundle/{id}](http://ideaconsult.github.io/examples-ambit/apidocs/#!/bundle/updateBundle) now accepts *status* field.

**Comment by vedina** [comment]
The `updated` field should be ok [now](http://sourceforge.net/p/ambit/code/6498)
