### ISSUE TITLE
Default ordering of models in the sidebar

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#111]
Default ordering of models in the sidebar (query page) should be by star, descending. Same for the datasets in the side bar.

(Currently it seems to be by model id)

**Comment by gonzomir** [comment]
Done, the two tables are sorted by the stars column when loaded.

**Comment by vedina** [comment]
The tables at [/data](https://apps.ideaconsult.net/data/ui/_search) are not sorted.  Is anything missing?

**Comment by gonzomir** [comment]
The file `ui-query.js` is not updated, look for line 11 in the commit diff:
https://github.com/ideaconsult/Toxtree.js/commit/e5824058c6699880f7ce135ce3cd501e5a08f1da#diff-21b7f88a18eab1fc2dcbfbb79e36e122R11

**Comment by vedina** [comment]
Confirmed.
