### ISSUE TITLE
Deleted data in RA matrix

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#112]
Deleted data in working matrix should be labelled in red, and should remain as it is even after “save”. 
The reason is to be able to check why it has been deleted at a later point in time. Only in the final matrix, the deleted data should not be visible

The JSON contains the deleted data , hence it should be possible to retain the visualisation.

**Comment by gonzomir** [comment]
Deleted data remains, labelled in red and with info icon that shows why it has been deleted in the same type of box, but without the "delete" button.
