### ISSUE TITLE
Error message appears when creating Data matrix at first time

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#114]
![image](https://cloud.githubusercontent.com/assets/211190/7427476/f08b1c48-efe4-11e4-90bf-8a27ed93f967.png)

**Comment by gonzomir** [comment]
Can you give more details, I am not able to reproduce it.

**Comment by vedina** [comment]
Client doesn't provide details, considers this low priority.  Moving to next milestone.

**Comment by vedina** [comment]
Might be already fixed
