### ISSUE TITLE
Dynamic retrieval of the user names for RA

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#115]
Could we use a tokenize library allowing to fill in the users dynamically (to extend #108).

If the current one supports this, what is the JSON format?

**Comment by gonzomir** [comment]
The current UI widget supports this, it makes AJAX request as the user types and populates the autocomplete list with values from a JSON like this:
```
[
  { "value": "1", "text": "Alan J. Heeger (United States)" },
  { "value": "2", "text":  "Alan G. MacDiarmid (United States, New Zealand)" }
]
```
The exact JSON fields are confugarble, the name of the search query param is also configurable.

**Comment by vedina** [comment]
How can I specify URI for the AJAX request and be able to prepopulate the list with already assigned users (another ajax request)

![image](https://cloud.githubusercontent.com/assets/211190/7470422/9fd471f2-f325-11e4-9f95-a6f04d7fd2b5.png)


* Be able to retrieve not the entire list once, but query depending on the typed in symbols
````
 /myaccount/users?q=Ni&media=application/json
````
* Be able to prepopulate the lists with users having read and write access respectively
````
/myaccount/users?bundle_uri=BUNDLEURI&media=application/json&mode=R|W
````

See the current [implementation with tokeninput JS library](https://apps.ideaconsult.net/data/scripts/ra/ui-matrix.js)

**Comment by vedina** [comment]
For update - what is the preferred approach ?

*  send a request to the server for each added / removed entry
* update all the access rights at once 

Is there existing (POST/PUT) query supported by the library ?

**Comment by gonzomir** [comment]
To prepopulate the list we will make a request before initializing the widget, fill the `select` with `option`s and select them. When we are initializing the widget, we should provide the URL for searching users as an option, the same as the current implementation.

For updating there is no build-in functionality, because the general use of such widgets is in forms that will be submitted as a whole - there is a `select` element with `multiple` attribute, which sends all the selected items. We can go either way - updating all rights at once will save some requests to the server.

**Comment by vedina** [comment]
OK 
Up to you to decide which tokenizer library to use, I'll update the JSON format accordingly.  Currently `/myaccount` queries only work for logged in users at `/opentox` server. 

If updating at once do we need a separate button to initiate the update?

**Comment by gonzomir** [comment]
No, I don't think so, we can use the `onblur` or `onchange` event.

**Comment by vedina** [comment]
Let's do then POST

**Comment by vedina** [comment]
Let's do application/x-www-form-urlencoded POST , in addition to the multiselect field will need the bundle_uri and the mode options

````
curl -d "bundle_uri=BUNDLEURI" -d “mode=W|R”  "/myaccount/users"
````

**Comment by gonzomir** [comment]
Implemented. The users are updated on every add/remove, because it works better this way with the widget.
