### ISSUE TITLE
Assessment identifiers tab update

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#118]
Replace the `Published` field  ( #106 ) with field `Status` displaying the field value (`draft`,`publiched`,`archived`) and allowing entering these values.

![image](https://cloud.githubusercontent.com/assets/211190/7675838/ddd9cfae-fd45-11e4-8b8d-ef6ecb7db975.png)

**Comment by gonzomir** [comment]
Is it possible status to have more than one value at a time?

**Comment by vedina** [comment]
No

**Comment by vedina** [comment]
Please update the `Published` field as specified.

**Comment by gonzomir** [comment]
The field is updated.
