### ISSUE TITLE
Substance tags in the working matrix

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#123]
enable manually assignment of substance tags in the working matrix (in the first column) @gonzomir  

`target` T
`source`  S
`category member` CM

Note substance tags and structure tags are different.

TODO : server side support

**Comment by vedina** [comment]
Server side implemented r6677 

* Adding substances to bundle now takes tag and remarks parameters, just as adding chemicals.
* [API docs](http://ideaconsult.github.io/examples-ambit/apidocs/#!/bundle/updateSubstanceInBundle)

**Comment by gonzomir** [comment]
Implemented manual tagging, but to show the selected tag properly, we will need `dataEntry`s in the dataset, returned by `matrix/working` and `matrix/final`, to have non-empty `bundles` property.

**Comment by vedina** [comment]
Server side implemented since [r6701](http://sourceforge.net/p/ambit/code/6701)
