### ISSUE TITLE
Clickable "Assessment DocLink" 

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#126]
If the "DOC Link" field is  URI, make it clickable

**Comment by gonzomir** [comment]
In the Assessment Identifiers tab the field can'be clickable since it is `input` element so that it can be edited. It can be clickable in the report thou.

**Comment by vedina** [comment]
OK, let it be clickable in the report for now.
We can think of options for both input field and clickable in the next version.

**Comment by vedina** [comment]
To be included in #140
