### ISSUE TITLE
Additional tag for structures - "CM"

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#127]
The tag options should be 

`T` (target)
`S` (source)
`CM` (category member)

**Comment by gonzomir** [comment]
Added the tag option, but it seems the server is not ready - it return error when trying to set the new tag on a structure:
```
net.idea.modbcum.p.ProcessorException: 
[Default processor]com.mysql.jdbc.MysqlDataTruncation: 
Data truncation: Data too long for column 'tag' at row 1	at
net.idea.modbcum.p.StatementExecutor.process(StatementExecutor.java:153)...
```

**Comment by vedina** [comment]
Can you try with just "CM"  (this is what is to be displayed anyway) ?

**Comment by gonzomir** [comment]
Works this way, fixed tag buttons to send "cm" and display tags properly.

**Comment by vedina** [comment]
the CM tag is working in collect structures, however , the tag column is empty in `endpoint data used`/`select substance` table.

![untitled](https://cloud.githubusercontent.com/assets/211190/8276030/79ee1e8e-18b9-11e5-9483-a6e975e21844.png)

**Comment by gonzomir** [comment]
This was a bug introduced while working on #130. Fixed.
