### ISSUE TITLE
The similarity column in the Collect structures tab is missing

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#128]
The similarity column in the `Collect structures` tab is missing

Could it be added back ?

**Comment by vedina** [comment]
Still missing. Please add the similarity column back in `Collect structures` tab (when doing similarity search). It is an essential information for similarity searching and structure selection.

**Comment by gonzomir** [comment]
Figured it out, the column is visible only when similarity search is done.
