### ISSUE TITLE
Read across report generation

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#130]
According to the provided template.

**Comment by vedina** [comment]
As a start looks good!

Outstanding issues:
* Please align the identifiers list and titles as shown in the Assessment tab  here (left)
![untitled 1](https://cloud.githubusercontent.com/assets/211190/8276171/b95e4c7c-18bb-11e5-9c50-dd59763d0fed.png)
* The `The original assessment in Ambit can be found via “Assessment ID��?.` looks broken. Probably it should include a link?
* The layout in the `Assessment matrix` looks broken (only first compound is visible, even the second column is truncated).

![untitled1](https://cloud.githubusercontent.com/assets/211190/8276210/2b61ed6a-18bc-11e5-8956-d20b1f551155.png)

* Is it already possible to generate PDF ?

Minor: 
* Initially the `report` tab is disabled. If a matrix is created , it is not enabled, until  a page refresh.

**Comment by gonzomir** [comment]
The identifiers in the report are updated, also fixed few bugs. The layout in the assesment matrix is broken because the `ui-matrix.css` stylesheet is not updated on the server, it is missing almost all the styles for the report at the bottom, also the print styles that we plan to use for PDF creation are not there.

**Comment by vedina** [comment]
Typo in Report section `3. List of substances related to the structures`   :  	Disagram -> 	Diagram

**Comment by vedina** [comment]
The structure diagrams itself (the pictures) should be shown in all relevant sections of the report

**Comment by vedina** [comment]
Fix display when Substance UUID is null

![image](https://cloud.githubusercontent.com/assets/211190/8636931/f6228250-2882-11e5-95d6-f0ae933e20e9.png) , see https://apps.ideaconsult.net/data/bundle/9

**Comment by vedina** [comment]
Closing, as the initial generation is in place, continue with improvements #140
