### ISSUE TITLE
zero values display

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#132]
If an effect record contains zero value it should be displayed as zero and not as in the screenshot 

````
"result":	{
	"unit":	"%",
	"loValue":	0
	}
````

![image](https://cloud.githubusercontent.com/assets/211190/8154812/a62965da-1346-11e5-87b7-b6cd3a8af59a.png)

**Comment by gonzomir** [comment]
Fixed the issue, the problem was that the value was casted to boolean, and numeric 0 equals false.

**Comment by vedina** [comment]
Resolved.
