### ISSUE TITLE
please merge your branch(es) with master

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#133]
Master is now merged with `matrix_rearrangements` branch.

However, @gonzomir  please merge your branch(es) with master (so that future merges become less complicated) and even better please use fork/pull in future as described here  (by @kerberizer )

**Comment by gonzomir** [comment]
I merged (as in `git merge`) `matrix_rearrangements` branch. The only other branch I worked on - `final_matrix` - doesn't need to be merged, as all it's commits are cherry-picked in `master`.

What do you mean by "use fork/pull in future"? To fork the project and use pull requests?

**Comment by vedina** [comment]
Yes, thanks for merging.

Fork/Pull - yes, makes life a bit easier at GitHub. Apologies,  seems I have missed the [link](https://github.com/ideaconsult/etc/wiki/GitHub-Collaboration-Best-Practices) .

But let's complete `Read Across 1.2` this week with the current approach with the branches.
