### ISSUE TITLE
Missing fields in Matrix

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#136]
These should be defined as `inMatrix:true` , but do not appear in the matrix
* 7.8.2 TO_DEVELOPMENTAL_SECTION
`effect type`

* 7.7. TO_CARCINOGENICITY_SECTION
`effect type`

4.3. PC_BOILING_SECTION
`atm. pressure` 

![untitled](https://cloud.githubusercontent.com/assets/211190/8334128/efd4ffa0-1a9e-11e5-9452-94f455f64d8c.png)

[Example (initial matrix)](https://apps.ideaconsult.net/data/ui/assessment?bundle_uri=https%3A%2F%2Fapps.ideaconsult.net%2Fdata%2Fbundle%2F38#)

**Comment by gonzomir** [comment]
Problem solved, these conditions have whitespace in their names, so the dotted notation did not work for them. The bracket notation is more error-prone in such cases.
