### ISSUE TITLE
Add XLSX link in the export tab

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#141]
Add link to export dataset & matrix as XLSX 

````
type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", icon: "images/xlsx.png
````

The XLSX icon  is in this [collection](https://github.com/kerberizer/ambit-flaticon) by @kerberizer

**Comment by gonzomir** [comment]
Where exactly the link should be? In the report tab?

**Comment by vedina** [comment]
No, in the Dataset export tab, next to e.g. CSV icon  (see below)

(not specific to assessment, should appear in all datasets)

![untitled](https://cloud.githubusercontent.com/assets/211190/8854970/569b3cd0-316b-11e5-9afc-233b695be5a4.png)

**Comment by vedina** [comment]
Yes, will be uploaded, adding link in JS is enough
