### ISSUE TITLE
IE10: (parsererror): SyntaxError: Invalid character

### ISSUE THREAD

**Issue by vedrin** [ideaconsult/Toxtree.js#15]
While testing in IE10 with the following SMILES:
O1C=C[C@H]([C@H]1O2)c3c2cc(OC)c4c3OC(=O)C5=C4CCC(=O)5
I've noticed that the first invocation of any model I've tried produces the following error reported at the bottom of the screen:
(parsererror): SyntaxError: Invalid character
The relevant entry in the browser's console log is:
SCRIPT5007: Unable to get property 'task' of undefined or null reference 
toxtree.js, line 427 character 3
Please note that a second attempt to apply the same model runs fine and produces the expected results. The problem seems to be specific to IE10, since I was not able to reproduce it in Chrome.

**Comment by sidramaraddy** [comment]
.
