### ISSUE TITLE
Ketcher doesn't work in ui-matrix

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#154]
In the new ui-matrix Ketcher is misplaced and doesn't work. Please fix.

![image](https://cloud.githubusercontent.com/assets/211190/10948944/fea1cee8-8338-11e5-90c8-679b05806b0c.png)

**Comment by vedina** [comment]
The search bar widget appears twice, this is likely to the new line in [ui-matrix.js](https://github.com/ideaconsult/Toxtree.js/blob/master/uses/ui-matrix.js#L67) to preinitialize the toolkits.

@gonzomir , @thejonan could you tell how to disable the initialization for the search widget?  Search/ketcher works fine in other pages where `ui-matrix.js` is not present.

**Comment by gonzomir** [comment]
OK, this line is a left-over from when the report was part of `ui-matrix.html` and it's not needed any more.
