### ISSUE TITLE
Internet Explorer issue : the selection lists are open by default

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#164]
The screenshot shows the screen right after clicking on the “+” icon in working matrix.  

The selection lists are open by default and prevent using the form. IE only issue, works OK in Chrome. 

![image](https://cloud.githubusercontent.com/assets/211190/11363370/2b87ac16-92a2-11e5-8b95-543178284651.png)

**Comment by vedina** [comment]
@gonzomir , @thejonan  - this is still an open issue, could you please look it up.

**Comment by gonzomir** [comment]
I thing I managed to fix this, or more precisely to avoid the issue. I couldn't get to the root of the problem - i.e. why IE opens the autocomplete menu while other browsers don't - but avoided it by returning empty result when the search term is empty in the function, supplied as a source option to the autocomplete widget. See #193.
