### ISSUE TITLE
Report sections 2/3 issues

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#167]
Related to #149 
The values for this [report](https://apps.ideaconsult.net/data/ui/assessment?bundle_uri=https%3A%2F%2Fapps.ideaconsult.net%2Fdata%2Fbundle%2F9) don't seem right

![image](https://cloud.githubusercontent.com/assets/211190/11358951/157070b0-9280-11e5-85e3-79a844e00065.png)

There should be no "medium" condition for `genetic tox in vitro` nor  "std_dev" (it's not a condition anyway). Could you check where these come from?

The table has a column endpoint, but this should not be visible for this `genetic invitro` section. Also formatting should match the one as in the matrix, not a generic table as in the popup.  

![image](https://cloud.githubusercontent.com/assets/211190/11358986/63f4b6a6-9280-11e5-946a-3c739f7ce2c1.png)

**Comment by gonzomir** [comment]
Can't tell why, but this data comes from the dataset. The feature has the following structure:
```
{
  "type":"Feature",
  "title":"",
  "units":null,
  "isNominal":false,
  "isNumeric":false,
  "isMultiValue":true,
  "sameAs":"http://www.opentox.org/echaEndpoints.owl#TO_GENETIC_IN_VITRO",
  "isModelPredictionFeature":true,
  "creator":"Just lsdfjlka sj",
  "order":1007,
  "source":{
    "URI":"https://apps.ideaconsult.net/data/dataset/Just+lsdfjlka+sj",
    "type":"read-across from supporting substance (structural analogue or surrogate)"
  },
  "annotation":[
    {"type":"conditions","p":"medium","o":"  "},
    {"type":"conditions","p":"metabolic activation","o":"  "},
    {"type":"conditions","p":"metabolic activation system","o":"  "},
    {"type":"conditions","p":"species","o":"  "},
    {"type":"conditions","p":"std_dev","o":"=3.4  mg/l"}
  ],
  "URI":"https://apps.ideaconsult.net/data/property/TOX/TO_GENETIC_IN_VITRO_SECTION//90CFAAC9D295E4A294963D1EF57B386CC01C30DC/Read-across/9a425a8d-23bc-3c9c-ba9b-a529c970081b"
}
```
As one can see, the annotations contain conditions "medium" and "std_dev".

Could it be a bug with adding endpoint data? Will the server accept such data?

**Comment by vedina** [comment]
Not sure why this is disturbing :)  

`std_dev` is an artifact , but `medium` is ok, and annotations are fine overall .  The datasets in bundles are generated from study data, and conditions and parameters go into feature annotations. Could you explain what's the issue?

**Comment by gonzomir** [comment]
The issue reported is that in annex 3 in the report the data is displayed incorrectly:

> There should be no "medium" condition for genetic tox in vitro nor "std_dev" (it's not a condition anyway). Could you check where these come from?

**Comment by vedina** [comment]
could you tell which substance it is?

**Comment by gonzomir** [comment]
The substance is formaldehyde (IUC4 DSN 52) - the first one in the assessment.

**Comment by vedina** [comment]
OK, the [study itself](https://apps.ideaconsult.net/data/substance/IUC4-efdb21bb-e79f-3286-a988-b6f6944d3734/study?top=TOX&category=TO_GENETIC_IN_VITRO_SECTION&media=application/json) is intact, looking what's going with matrix generation
