### ISSUE TITLE
Assessment report layout improvements

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#171]
* Remove the `Company` field in the report 

* Make `Assessment Doclink` clickable in the Word file  (see also #126)

* An idea to make `Assessment Doclink` clickable in assessment tab - leave the input text field as it is, but provide a button /link that leads to the link . Could be some JS reading the text field and opening the linked page  in a separate tab. (the reason is the link could be very long and it is inconvenient to copy/paste it)

* in the html report the doclink url is broken  in IE (works in FF and Chrome)

**Comment by gonzomir** [comment]
Some things not mentioned in #176:

The library we use for DOCX generation does not support hyperlinks in the template file. So a custom plugin will need to developed for this and it will take more time. 

For me the docLink works OK in IE. Can you provide more details? A bundle URI and IE version will do. Please, note that the docLink is clickable only if it is valid URL. The check is taken from this gist: https://gist.github.com/searls/1033143 and matches strings that begin with `http` or `www.`

**Comment by vedina** [comment]
The issue with the doclink is it may be very large and can be actually not web URL, but e.g. windows file path to a shared drive.  

The solution suggested in December was to allow convenient copying of this long string (similar to the way UUID is copied) and let the user paste it into a browser or elsewhere.

**Comment by vedina** [comment]
It seems in the docx report the `assessment code` displays the assessment ID
