### ISSUE TITLE
Fix the users to bundle assignments 

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#178]
Fix the users to bundles assignment as currently implemented #115 so that the users are NOT updated on every add/remove.  Important for performance and security reasons.

**Comment by gonzomir** [comment]
This will require unfortunately a button or another trigger to fire the update. We can't use `blur` or `change` event on the input because these events happen in the normal interaction with the widget white selecting users.

**Comment by vedina** [comment]
No problem, let be a button.

**Comment by vedina** [comment]
Could we have this fixed ASAP ?
