### ISSUE TITLE
Take into account URI parameters for studies

### ISSUE THREAD

**Issue by thejonan** [ideaconsult/Toxtree.js#53]
Filter the contents of studies tabs in _jToxStudy_ component, based on the passed `top`, `category` and `property_uri` URI parameters.

**Comment by vedina** [comment]
This is fixed since r6670

[example](https://apps.ideaconsult.net/data/substance/IUC4-efdb21bb-e79f-3286-a988-b6f6944d3734/study?top=TOX)
