### ISSUE TITLE
Custom icons 

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#56]
Could you design custom icons to be used  instead of the 
[folder icon](http://apps.ideaconsult.net:8080/data/ui/_search) and [Run, M & A buttons at toxtree page](http://apps.ideaconsult.net:8080/data/ui/toxtree).

Preferable size should be bigger than standard jQueryUI icons , e.g. 24х24 и 64х64 .

**Comment by vedina** [comment]
@kerberizer could we consider this by May 20?

**Comment by kerberizer** [comment]
@vedina, will do my best. Apologies for the awfully long delay.

**Comment by vedina** [comment]
@kerberizer
