### ISSUE TITLE
Popup box for entering data

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#76]
Apart from endpoint and value fields implemented currently, should allow entering of 

- selected study conditions
- protocol (optional, important for some endpoints)

We will get a list of what study conditions / protocol / protocol parameters are to be entered for each endpoint.  This could go into a configuration (reuse the config-study, or create a different one and merge).

**Comment by vedina** [comment]
Study conditions are available for each property via the condition field in 

/property/TOPCATEGORY/ENDPOINTCATEGORY?media=application/json  [example](https://apps.ideaconsult.net/data/property/ECOTOX/EC_FISHTOX_SECTION?media=application/json)

it would be good to be able to enter the specific conditions for each endpoint category. 

Entering the protocol should also be possible (text field)

**Comment by vedina** [comment]
Tried to enter "positive" value to "Genetic in vitro toxicity"
[TOX/TO_GENETIC_IN_VITRO_SECTION](https://apps.ideaconsult.net/data/bundle/6/matrix?media=application%2Fjson) , doesn't work yet.

**Comment by thejonan** [comment]
Conditions editing added e628586bb8022becc2cf1c62f0de50ed5bca39fb.
Put after saving they do not arrive back to the matrix. This is what is sent upon saving:

```
{
    "study": [{
        "owner": {
            "substance": {
                "uuid": "IUC4-efdb21bb-e79f-3286-a988-b6f6944d3734"
            }
        },
        "protocol": {
            "topcategory": "ENV FATE",
            "category": {
                "code": "TO_BIODEG_WATER_SCREEN_SECTION"
            },
            "endpoint": "5.2.1. Biodegradation in water - screening tests",
            "guideline": ["Justiadof aisdjf aioj "]
        },
        "citation": {
            "year": "2015",
            "title": "Refereneafdla"
        },
        "parameters": {},
        "interpretation": {
            "criteria": "Remakdsf laksfdj a"
        },
        "reliability": {
            "r_studyResultType": "2303"
        },
        "effects": [{
            "result": {
                "loQualifier": ">",
                "loValue": "4.5",
                "unit": "mg/l",
                "upValue": ""
            },
            "conditions": {
                "sampling time": {
                    "loValue": "36",
                    "units": "h",
                    "loQualifier": "=",
                    "upValue": ""
                }
            },
            "endpoint": "BOD"
        }
        ]
    }
    ]
}

```

**Comment by vedina** [comment]
There is no value field in the popup box of  [6.1.5 section](https://apps.ideaconsult.net/opentox/ui/assessment?bundle_uri=https%3A%2F%2Fapps.ideaconsult.net%2Fopentox%2Fbundle%2F1#)

![image](https://cloud.githubusercontent.com/assets/211190/5773338/fff8380a-9d69-11e4-82f8-3c3e4558cafa.png)

**Comment by vedina** [comment]
New issue in entering text values

![image](https://cloud.githubusercontent.com/assets/211190/5778978/cc17cb16-9da7-11e4-8318-0672d0f97207.png)

This is displayed as 

![image](https://cloud.githubusercontent.com/assets/211190/5778995/e9563f82-9da7-11e4-824e-0e52d253b7b9.png)

JSON received at the server while saving : 
````
{
    "study": [
        {
            "owner": {
                "substance": {
                    "uuid": "IUC5-541ccdba-0033-45ee-8136-406478deb0f4"
                }
            },
            "protocol": {
                "topcategory": "TOX",
                "category": {
                    "code": "TO_GENETIC_IN_VITRO_SECTION"
                },
                "endpoint": "7.6.1. Genetic toxicity in vitro",
                "guideline": [
                    "XXXXX7"
                ]
            },
            "citation": {
                "year": "2015",
                "title": "XXXXX6"
            },
            "parameters": {},
            "interpretation": {
                "result": "",
                "criteria": "XXXXX8"
            },
            "reliability": {
                "r_studyResultType": "1885"
            },
            "effects": [
                {
                    "result": {
                        "loValue": "1",
                        "loQualifier": "=",
                        "upValue": ""
                    },
                    "conditions": {
                        "metabolic activation system": {
                            "loValue": "3",
                            "loQualifier": "=",
                            "upValue": ""
                        },
                        "metabolic activation": {
                            "loValue": "4",
                            "loQualifier": "=",
                            "upValue": ""
                        },
                        "species": {
                            "loValue": "5",
                            "loQualifier": "=",
                            "upValue": ""
                        }
                    }
                }
            ]
        }
    ]
}
````
It looks like the text values XXXX1 are converted to numeric values instead. The result.textvalue is missing and the interpretation.result is empty (should be XXXXX2).

**Comment by thejonan** [comment]
Fixes here in 71bb1d0ac9d3b6bb02d807049160a46d55862036

**Comment by vedina** [comment]
The issue above is resolved.

The screenshot below is a result of entering in the value field _"3.14 >  mg/l"_ . The string after the value goes into the units. 

![image](https://cloud.githubusercontent.com/assets/211190/5792096/4f9ff27a-9f0f-11e4-8796-588c762cf634.png) [JSON](https://apps.ideaconsult.net/opentox/bundle/1/matrix?media=application%2Fjson) 

We might ignore this for now.

**Comment by thejonan** [comment]
Yes, I see, but that is expected. What is the expected behavior for this value: 3.14 > mg/l? Currently `<`, `<=`, `=`, `>=` and `>` are put _before_ the value and this is how it is parsed.

**Comment by vedina** [comment]
it is basically an invalid entry.
