### ISSUE TITLE
RA Matrix lifecycle

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#78]
The initial matrix is populated automatically from selected sources. Editing is not allowed. 
The working matrix is the initial matrix + manually added (or removed) values.
There could be multiple working matrices – snapshots over time (e.g. allow storing current WM).
The Final matrix is a fixed copy of the working matrix.

Discussed where there could be more than one Final  matrix ? (a new copy if more data comes later). Not decided. The same could be achieved via creating a copy of the assessment.

**Comment by vedina** [comment]
See 20.-24. [here](https://github.com/ideaconsult/examples-ambit/blob/master/ambit-json-docs/bundle.md )

The initial matrix is constructed on the fly based on the substance and endpoint selection in a /bundle/{id}. The initial matrix is available at /bundle/{idbundle}/dataset 

The working matrix created by request (see [20.](https://github.com/ideaconsult/examples-ambit/blob/master/ambit-json-docs/bundle.md )  and [API](http://ideaconsult.github.io/examples-ambit/apidocs/#!/bundle/createMatrixFromBundle).  It is available at /bundle/{idbundle}/matrix . 

The /bundle/{id}/summary returns a row indicating if the working matrix is created or not.

**Comment by thejonan** [comment]
Are we better here?

**Comment by vedina** [comment]
Almost . 

Can you pls add the same style of behaviour for creating a final matrix 

- check if the final matrix is created via /bundle/{idbundle}/summary [API](http://ideaconsult.github.io/examples-ambit/apidocs/#!/bundle/getBundleSummary)
- Create the final matrix if POST /bundle/{idbundle}/matrix/final [API](http://ideaconsult.github.io/examples-ambit/apidocs/#!/bundle/createMatrixFromBundle) 
- Retrieve the final matrix via /bundle/{idbundle}/matrix/final [API](http://ideaconsult.github.io/examples-ambit/apidocs/#!/bundle/getBundleMatrix)

**Comment by thejonan** [comment]
It means that "final matrix" is not a stage of _the_ matrix, but a separate entity that is based on the edited matrix, but has it's own "lifecycle". Correct?

**Comment by vedina** [comment]
Yes, it is a separate entity.

**Comment by gonzomir** [comment]
I implemented creating a final matrix from the working. It's not editable and the button for initiating the action is only visible if working matrix exists.

Should we disable the "final matrix" tab if there isn't working copy?

**Comment by vedina** [comment]
yes, please.

**Comment by gonzomir** [comment]
Done. Initially the final matrix tab is disabled unless there is working or final matrix. When working copy is created the tab is enabled.

**Comment by vedina** [comment]
Just after creating the final matrix it appears with the editable + / - buttons
the editing appears to work but in fact it edits the working matrix.
On refresh the final matrix shows  correctly.

Otherwise works as expected.

**Comment by gonzomir** [comment]
Fixed the editable state of the final matrix and also the visibility of the "save" button.
