### ISSUE TITLE
configurable query for retrieving feature lists 

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#81]
Proposal to provide an explicit query for retrieve the dataset columns, instead of guessing from the first record.  Not all datasets are supposed to have all features in the first record; and for some datasets the list of ffeatures is well knowm (/dataset/id have all feature list in /dataset/id/feature).  Also could be faster.

For example [here](http://apps.ideaconsult.net:8080/enanomapper/substanceowner/NWKI-9F4E86D0-C85D-3E83-8249-A856659087DA/dataset) the data is very sparse and the first record has value for only one feature. But we can provide a query to retrieve all features.

**Comment by vedina** [comment]
How to use the featureURI parameter - it doesn't seem to work as below

````
<div class="jtox-toolkit" data-kit="compound" 
	data-configuration="config_dataset"
	featureUri="http://localhost:8080/ambit2/bundle/12/property" 
	data-cross-domain="false"	
	data-show-export="yes"
	data-on-details="onDetailedRow"
	data-dataset-uri="http://localhost:8080/ambit2/bundle/12/matrix"
	data-tabs-folded="true"
	data-on-error="errorHandler" 
	data-jsonp="false">
	</div>
````

**Comment by thejonan** [comment]
Yes, it should be `data-feature-uri`, this is the convention for all `data-XXX` parameters - each dash is removed and next word - capitalized (after removing the initial `data-`, of course).

Refer here: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes

**Comment by vedina** [comment]
ok
