### ISSUE TITLE
Option to prevent structures with no data showing in RA 

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#84]
Option to have a search filter, which prevents that structures in the read across/category workflow will be selected which have no data (this would prevent unnecessary work and would avoid frustration of the user).

to be supported server side and client side

**Comment by vedina** [comment]
Introduce a new option (checkbox?) in the search component.

Use the ?filterBySubstance=true for the similarity substructure queries to restrict the search within the chemical structures with assigned substances.  Should be available in the “Collect structures” tab of the read across workflow (and / or in the general search).

````
/query/similarity 
/query/smarts 
````

**Comment by vedina** [comment]
@gonzomir Can we get this working this week?

**Comment by gonzomir** [comment]
Added the option in the search widget of jToxQuery kitq so that it is available everywhere the widget is used, including in read across.
