### ISSUE TITLE
timestamp in Assessment identifiers tab

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#90]
Assessment identifier [example](https://apps.ideaconsult.net/data/ui/assessment?bundle_uri=https%3A%2F%2Fapps.ideaconsult.net%2Fdata%2Fbundle%2F1)

1) Convert the unix timestamp  (field `created` ) to a human readable date .

2) Enable storing of the Purpose text box (field `description`) (

![image](https://cloud.githubusercontent.com/assets/211190/5792706/e5d1b570-9f2e-11e4-9951-91b4b1d8fe94.png)

[API on create](http://ideaconsult.github.io/examples-ambit/apidocs/#!/bundle/createBundle)
[API on edit](http://ideaconsult.github.io/examples-ambit/apidocs/#!/bundle/updateBundle)
[API on read](http://ideaconsult.github.io/examples-ambit/apidocs/#!/bundle/getBundleByID) and example JSON 

````json
{"dataset": [
{
	"URI":"https://apps.ideaconsult.net/data/bundle/1",
	"type":"Bundle",
	"title":"Back To the title1",
	"stars":5,
	"source":"Test",
	"rightsHolder":"Test",
	"maintainer":"Unknown",
	"seeAlso":"Test",
	"rights":{
		"URI":"http://ambit.sf.net/resolver/rights/Test",
		"type":"rights"
	},
	"id":1,
	"description":"Test assessment",
	"created":1416672317000,
	"summary":"https://apps.ideaconsult.net/data/bundle/1/summary",
	"compound":"https://apps.ideaconsult.net/data/bundle/1/compound",
	"substance":"https://apps.ideaconsult.net/data/bundle/1/substance",
	"property":"https://apps.ideaconsult.net/data/bundle/1/property",
	"dataset":"https://apps.ideaconsult.net/data/bundle/1/dataset",
	"matrix":"https://apps.ideaconsult.net/data/bundle/1/matrix"
}
]
}
````

**Comment by gonzomir** [comment]
The `created

**Comment by gonzomir** [comment]
The `created` field is now displayed in dd.mm.yyyy format. The format is hardcoded in `ccLib.js`.

The Purpose text box is now properly stored and displayed, just changed the property name reference.

Changes are in commit 1d8fef416, forgot to reference the issue in commit message.

**Comment by vedina** [comment]
confirmed
