### ISSUE TITLE
Toxtree UI not working

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#91]
@thejonan @gonzomir Could you please check 

https://apps.ideaconsult.net/data/ui/toxtree 

- Entering 50-00-0 in the search box retrieves the compound details, but does not show the structure
- Launching calculations gives the following error

````
https://apps.ideaconsult.net/data/ui/undefined Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
````

Possible reasons:
- Recent server URL changes @kerberizer 
- Recent jToxKit updates ?

**Comment by kerberizer** [comment]
There has been some misconfiguration on the Apache TLS proxy side, which now is corrected, so perhaps this bug is gone too.

**Comment by vedina** [comment]
The TLS related issue is gone, there is still JavaScript related issue 

1) The URI /ui/undefined  is not valid and should not be called

2) Error when running predictions :

````
 Uncaught TypeError: Cannot read property 'indexOf' of undefinedjtoxkit.js:696 window.jT.window.jToxKit.calljtoxkit.js:3051 (anonymous function)jtoxkit.js:61 ccLib.fireCallbackjtoxkit.js:730 (anonymous function)jtoxkit.js:61 ccLib.fireCallbackjtoxkit.js:619 window.jT.window.jToxKit.pollTaskjtoxkit.js:614 (anonymous function)jtoxkit.js:61 ccLib.fireCallbackjtoxkit.js:717 self.$.ajax.successjquery-1.10.2.js:3048 jQuery.Callbacks.firejquery-1.10.2.js:3160 jQuery.Callbacks.self.fireWithjquery-1.10.2.js:8235 donejquery-1.10.2.js:8778 jQuery.ajaxTransport.send.callback
````

**Comment by thejonan** [comment]
I can't the first error, although I saw it two days ago. I did manage to reproduce the second one and fixed it.

**Comment by vedina** [comment]
Toxtree JS user interface is still giving JS error, where it has no cached results and needs to run predictions. To reproduce the JS error  

Enter CCCCCCCCCC=O in the search box

https://apps.ideaconsult.net/data/ui/toxtree

````
Uncaught TypeError: Cannot read property 'indexOf' of undefinedjtoxkit.js:705 window.jT.window.jToxKit.calljtoxkit.js:3062 (anonymous function)jtoxkit.js:61 ccLib.fireCallbackjtoxkit.js:739 (anonymous function)jtoxkit.js:61 ccLib.fireCallbackjtoxkit.js:628 window.jT.window.jToxKit.pollTaskjtoxkit.js:623 (anonymous function)jtoxkit.js:61 ccLib.fireCallbackjtoxkit.js:726 self.$.ajax.successjquery-1.10.2.js:3048 firejquery-1.10.2.js:3160 self.fireWithjquery-1.10.2.js:8235 donejquery-1.10.2.js:8778 callback
````

**Comment by gonzomir** [comment]
I think I found the bug - the call to apply the model was checking for the full task object, while it receives only the result. Fixed in master.

**Comment by vedina** [comment]
Could you please ensure the code expects the result URI only when the HTTP code is 200, otherwise it should expect the full task object.

**Comment by gonzomir** [comment]
The server return task object, but the call is made through `jToxKit.service` method, which polls the task and fires the callback with the task result when completed successfully and with `null` on error. So the code in `toxmodel.js` looks like this:
```
jT.service(self, modelUri, { method: "POST", data: { dataset_uri: datasetUri } }, function (result, jhr) {
  if (!result)
    ccLib.fireCallback(callback, self, null, jhr);
  else
    jT.call(self, result, callback);
});
```
That's where the callback receives only the result instead of the full task object.

**Comment by vedina** [comment]
ok, thanks for the clarification!

**Comment by vedina** [comment]
Confirmed this is fixed
