### ISSUE TITLE
Displaying units in result values in jToxStudy tabs

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#93]
Units are missing for result values in jToxStudy . The JSON is intact (effects.result.unit )

Example: See [P-Chem/Melting point](https://apps.ideaconsult.net/data/substance/IUC4-efdb21bb-e79f-3286-a988-b6f6944d3734/study). 

````
{
    "uuid": "IUC4-7fe66286-4e2a-31c8-836f-f3fb38ce8e6d",
    "owner": {
        "substance": {
            "uuid": "IUC4-efdb21bb-e79f-3286-a988-b6f6944d3734"
        },
        "company": {
            "uuid": "IUC4-44bf02d8-47c5-385d-b203-9a8f315911cb",
            "name": "OECD / Paris / France"
        }
    },

 ....
    "effects": [
        {
            "endpoint": "Melting Point",
            "result": {
                "unit": "°C",
                "loValue": -92
            }
        }
    ]
}
````

The units for conditions and parameters are displayed correctly.

**Comment by gonzomir** [comment]
If I got it right, the issue is fixed. The formatting function `jToxKit.ui.renderRange` was called omitting the `units` param and the `type` was `undefined` instead of the value provided. I set the `units` to `null`, because in this case units are taken from the `data`.

**Comment by vedina** [comment]
confirmed this is fixed
