### ISSUE TITLE
Generate new assessment version

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#96]
Rename the button “Duplicate” in the “Assessment Identifier” to “Generate new version”.

Use [POST /bundle/{id}/version  API](http://ideaconsult.github.io/examples-ambit/apidocs/#!/bundle/createBundleVersion) to obtain the new version (it will be another /bundle/{id}). Launch the assessment editor of the new bundle.

Bundle versions can be retrieved via [GET /bundle/{id}/version](http://ideaconsult.github.io/examples-ambit/apidocs/#!/bundle/getBundleVersionsByID)

**Comment by gonzomir** [comment]
Implemented as requested.
