### ISSUE TITLE
Rename column "Reason"

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#97]
Rename the column “Reason” (Assessment / collect Structures tab)  to “Rationale” . Enable sorting on this column.

**Comment by gonzomir** [comment]
Renamed. Changes are in matrix_rearrangements branch.

**Comment by vedina** [comment]
Can we have the "Rationale" column sortable?

**Comment by vedina** [comment]
The column rationale in "Collect structures" tab should be editable - in order to select the structure as Target or Source and write down the reason for the selection.

**Comment by gonzomir** [comment]
Fixed table sorting and the bug with editing the rationale - had to move the columns back to the second variable table.

**Comment by vedina** [comment]
The editing is fixed, however, the "Rationale" column is neither sortable nor searchable.

**Comment by gonzomir** [comment]
I made the column searchable, sorting works for me.
