### ISSUE TITLE
Assessment/Endpoint data/Search substances  rearrangements

### ISSUE THREAD

**Issue by vedina** [ideaconsult/Toxtree.js#99]
There is requirement to organize the "Search substances" table based on structures selected and display the structure diagram and the defined tag. 

Selected structures first, then substances as details 
(columns as in #98). 
![image](https://cloud.githubusercontent.com/assets/211190/6614489/7ab1abf8-c8a3-11e4-8487-38164bef2458.png)

This is essentially the same as the structure browser in the Structure selected tab (or in the search page), with checkboxes for the substances. 

Additional wish list (under discussion):
- *only the 4 columns (Diagram, CAS RN, EC Number, Name) . The column “Names” should be as broad as possible to make the structure row as small as possible* . For now let's start with the existing setup with columns as in #98. However, the opening of the details (substance list) should not hide the parent row (the structure information).
- *The substance list should always be open to make clear that there is a “one structure to n substances” relationship*. Instead, proposed to have *Expand/Collapse All* button instead to make long lists usable.

**Comment by gonzomir** [comment]
The overall structure of the table is complete, but there is problem with the structure data. It is also present in the Collect Structures tab - the dataset  returned by `bundleUri/compunds` does not contain any values in `dataset.dataEntry[i].values`. That's why there is no data for the collected structures.

**Comment by vedina** [comment]
Could you please clarify. Is this specific to some assessment or for any bundle?
